### PR TITLE
Correct Sauce Labs API usage

### PR DESCRIPTION
**Pull request by sah**
Corrects a couple of issues with Sauce Labs API usage in the handling of mobile platforms. Mostly, this now trusts `long_name` to always be a human-readable name which works in the `deviceName` field.

Note that this changes guacamole IDs.

### CODE REVIEW

**Comment by Maciek416** [comment]
Thanks so much for this @sah !

**Comment by Maciek416** [comment]
Just to reduce confusion in case this PR sits around for a little whiel: We're going to set aside a bit of time (probably next week, or after next week) to fully absorb the impact of these changes on our end and document a transition for our users.

**Comment by sah** [comment]
Sounds good. I'm going to see if I can fix these failing tests. If there's some time, I may add a few more tweaks to this PR.

**Comment by sah** [comment]
Hey, just a reminder in the new year that this branch exists. I just handled some conflicts caused by linting changes in master, so this should be mergeable again.

**Comment by Maciek416** [comment]
Thanks for the update!

**Comment by Maciek416** [comment]
Conflict resolved against @jherr 's ES6 updates. Going to land this and publish a beta to test in our ecosystem.

**Comment by Maciek416** [comment]
Fixing lints

**Pull request merged**
